import mongoose from "mongoose";

const PlayerSchema = new mongoose.Schema({
  // User ID which will be auto generated
  // userName generated by user
  userName: { type: String, required: true },
  // screenName generated by user
  screenName: { type: String, required: true },
  // Games that are associated with the player
  games: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: "games",
    },
  ],
});

const Player = mongoose.model("players", PlayerSchema);

export default Player;
